spring:
  datasource:
    url: jdbc:mysql://localhost:3306/module?useSSL=false
    platform: 
    username: root
    password: webdev!
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true   
        enable_lazy_load_no_trans: true    
security:
  basic:
    enabled: false
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 9090